## TradingEnv-v0

### Open AI 'Gym' for reinforcement-learning based trading algorithms

This gym implements a very simple trading environment for reinforcement learning.

The gym provides daily observations based on real market data pulled from Quandl on, by default, the SPY etf.  An episode is defined as 252 contiguous days sampled from the overall dataset.  Each day is one 'step' within the gym and for each step, the algo has a choice:

 - SHORT (0)
 - FLAT (1)
 - LONG  (2)
 
If you trade, you will be charged, by default, 10 BPS of the size of your trade.  Thus, going from short to long costs twice as much as going from short to/from flat.  Not trading also has a default cost of 1 BPS per step.  Nobody said it would be easy!
 
At the beginning of your episode, you are allocated 1 unit of cash.  This is your starting Net Asset Value (NAV). 

### Beating the trading game 

For our purposes, we'll say that beating a buy & hold strategy, on average, over one hundred episodes will notch a win to the proud ai player.  We'll illustrate exactly what that means below.

### Let's look at some code using the environment


###  imports

In [1]:
import gym
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import interactive
interactive(True)
import gym_trading

env = gym.make('trading-v0')
#env.time_cost_bps = 0 # 

env = env.unwrapped



import tensorflow as tf
import policy_gradient

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: Environment '<class 'gym_trading.envs.trading_env.TradingEnv'>' has deprecated methods. Compatibility code invoked.


/Users/andrewplaate/miniconda3/envs/mlp/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
INFO:policy_gradient:policy_gradient logger started.


In [2]:
# create the tf session
sess = tf.InteractiveSession()

# create policygradient
num_actions=3  # same as # of stocks
Variables=3
obs_dim=num_actions*Variables
NumOfLayers=3
pg = policy_gradient.PolicyGradient(sess, obs_dim=obs_dim, num_actions=num_actions,NumOfLayers=NumOfLayers, learning_rate=1e-2 )

# and now let's train it and evaluate its progress.  NB: this could take some time...
df,sf = pg.train_model(env, episodes=25001, log_freq=100)#, load_model=True)


INFO:policy_gradient:year #     0, mean reward: -1463.3157, sim ret:   0.0000, mkt ret:   0.0000, net:   0.0000


[[-0.32168596 -0.34429076  0.33402328]]
[-1463.31574173]
[[-0.34663953  0.31386953 -0.33949094]]
[[-0.35587418 -0.27828277  0.36584305]]
[[-0.32454412  0.3382488  -0.33720708]]
[[-0.33295884  0.33422551  0.33281565]]
[[-0.35249802 -0.3048853   0.34261668]]
[[-0.31955699  0.34397196 -0.33647105]]
[[-0.31088522  0.33766357 -0.35145121]]
[[-0.35264142 -0.30774756 -0.33961102]]
[[-0.35540983  0.32756025 -0.31702992]]
[[-0.33562653 -0.33834603  0.32602744]]
[[-0.32030204  0.35891372  0.32078424]]
[[-0.36391721 -0.30191083 -0.33417195]]
[[-0.33600727  0.34857134  0.3154214 ]]
[[-0.29468444 -0.36655795 -0.33875761]]
[[-0.34607036 -0.31791667 -0.33601296]]
[[-0.3167392   0.33685852  0.34640228]]
[[-0.33505323  0.35181961  0.31312717]]
[[-0.31917039 -0.32569559 -0.35513402]]
[[-0.3272338  -0.34486201 -0.32790419]]
[[-0.34271217  0.32595721 -0.33133062]]
[[-0.33412238  0.3298957  -0.33598192]]
[[-0.33667721  0.34139613  0.32192666]]
[[ 0.31257719  0.35222995 -0.33519286]]
[[-0.35338173 -0.316647

INFO:policy_gradient:year #   100, mean reward: 214.4501, sim ret:   0.0000, mkt ret:   0.0000, net:   0.0000


[[-0.37728456 -0.30262078  0.32009466]]
[ 214.45005597]
[[-0.3385143  -0.33998822  0.32149749]]
[[-0.32511702 -0.33110111  0.34378187]]
[[-0.34832685 -0.3298768   0.32179635]]
[[-0.31552993 -0.35431023  0.33015985]]
[[-0.29065926 -0.34974048  0.35960026]]
[[-0.29217361 -0.35628638  0.35154   ]]
[[-0.35327004 -0.28344667  0.36328329]]
[[ 0.32030995  0.33388441 -0.34580564]]
[[-0.30508184 -0.36533751  0.32958064]]
[[ 0.33941749 -0.31267901 -0.34790351]]
[[-0.27702503 -0.38276554  0.34020943]]
[[-0.26783105 -0.37346925  0.3586997 ]]
[[-0.22396069 -0.40929849  0.36674083]]
[[-0.22725094 -0.41918708  0.35356198]]
[[-0.29482226 -0.35704663  0.34813111]]
[[-0.31720726 -0.36394733  0.3188454 ]]
[[-0.26908084 -0.3829969   0.34792226]]
[[-0.2705792  -0.35259295  0.37682785]]
[[-0.2265667  -0.38246602  0.39096728]]
[[ 0.32454008  0.35068819 -0.32477173]]
[[ 0.30292143 -0.35334224  0.34373633]]
[[ 0.38843503  0.29698116 -0.31458382]]
[[-0.22349063 -0.35043897  0.42607039]]
[[ 0.38362421  0.3283312

INFO:policy_gradient:year #   200, mean reward: -377.8893, sim ret:   0.0000, mkt ret:   0.0000, net:   0.0000


[[-0.33240599 -0.35225111  0.3153429 ]]
[-377.88931087]
[[ 0.30975663  0.33936197 -0.3508814 ]]
[[ 0.26378828  0.4159855  -0.32022621]]
[[ 0.26876098  0.40099486 -0.33024416]]
[[ 0.30695733  0.35362617 -0.3394165 ]]
[[-0.33774625 -0.32080289  0.34145086]]
[[ 0.29637948  0.37152128 -0.33209924]]
[[-0.35749482 -0.31470695  0.32779823]]
[[-0.35595602 -0.29794826  0.34609572]]
[[ 0.27626678  0.39117097 -0.33256225]]
[[ 0.23693764  0.45337965 -0.30968271]]
[[ 0.09413285  0.6834715  -0.22239565]]
[[ 0.29477019  0.35657695 -0.34865286]]
[[ 0.14946414  0.58945984 -0.26107602]]
[[ 0.19703448  0.4972486  -0.30571692]]
[[ 0.21198716  0.47317568 -0.31483716]]
[[-0.3390362  -0.34036589  0.32059791]]
[[-0.35281018 -0.31498476  0.33220506]]
[[ 0.11450247  0.61932115 -0.26617638]]
[[-0.36856446  0.28819853 -0.34323702]]
[[ 0.18059004  0.47394945 -0.34546051]]
[[ 0.14631035  0.57683582 -0.27685383]]
[[ 0.19048315  0.50611643 -0.30340042]]
[[ 0.24011589  0.41555365 -0.34433046]]
[[ 0.30472248  0.3641055

KeyboardInterrupt: 

### Results

Policy gradients beat the trading game!  That said, it doesn't work every time and it seems, looking at the charts below, as though it's a bit of a lucky thing.  But luck counts in the trading game as in life!


In [ ]:
sf['net'] = sf.simror - sf.mktror
#sf.net.plot()
sf.net.expanding().mean().plot()
sf.net.rolling(100).mean().plot()

In [ ]:
sf.net.rolling(100).mean().tail()