## TradingEnv-v0

### Open AI 'Gym' for reinforcement-learning based trading algorithms

This gym implements a very simple trading environment for reinforcement learning.

The gym provides daily observations based on real market data pulled from Quandl on, by default, the SPY etf.  An episode is defined as 252 contiguous days sampled from the overall dataset.  Each day is one 'step' within the gym and for each step, the algo has a choice:

 - SHORT (0)
 - FLAT (1)
 - LONG  (2)
 
If you trade, you will be charged, by default, 10 BPS of the size of your trade.  Thus, going from short to long costs twice as much as going from short to/from flat.  Not trading also has a default cost of 1 BPS per step.  Nobody said it would be easy!
 
At the beginning of your episode, you are allocated 1 unit of cash.  This is your starting Net Asset Value (NAV). 

### Beating the trading game 

For our purposes, we'll say that beating a buy & hold strategy, on average, over one hundred episodes will notch a win to the proud ai player.  We'll illustrate exactly what that means below.

### Let's look at some code using the environment


###  imports

In [ ]:
import gym
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import interactive
interactive(True)
import gym_trading


### create the environment

This may take a moment as we are pulling historical data from quandl.

In [ ]:
env = gym.make('trading-v0')
#env.time_cost_bps = 0 # 


### the trading model

Each time step is a day.  Each episode is 252 trading days - a year.  Each day, we can choose to be short (0), flat (1) or long (2) the single instrument in our trading universe.

Let's run through a day and stay flat.

In [ ]:
observation = env.reset()
done = False
navs = []
while not done:
    action = 1 # stay flat
    observation, reward, done, info = env.step(action)
    navs.append(info['nav'])
    if done:
        #print 'Annualized return: ',navs[len(navs)-1]-1
        pd.DataFrame(navs).plot()


### Note that you are charged just for playing - to the tune of 1 basis point per day!


### Rendering

For now, no rendering has been implemented for this gym, but with each step, the following datum are provided which you can easily graph and otherwise visualize as we see above with the NAV:

 - pnl - how much did we make or lose between yesterday and today?
 - costs  - how much did we pay in costs today
 - nav    - our current nav
 

## utility methods: running strategies once or repeatedly

Although the gym can be 'exercised' directly as seen above, we've also written utility methods which allow for the running of a strategy once or over many episodes, facilitating training or other sorts of analysis.

To utilize these methods, strategies should be exposed as a function or lambda with the following signature:

`Action a = strategy( observation, environment )`
    
Below, we define some simple strategies and look briefly at their behavior to better understand the trading gym. 

In [ ]:
import trading_env as te

stayflat     = lambda o,e: 1   # stand pat
buyandhold   = lambda o,e: 2   # buy on day #1 and hold
randomtrader = lambda o,e: e.action_space.sample() # retail trader

# to run singly, we call run_strat.  we are returned a dataframe containing 
#  all steps in the sim.
env = env.unwrapped
bhdf = env.run_strat(buyandhold)

print(bhdf.head())

# we can easily plot our nav in time:
bhdf.bod_nav.plot(title='buy & hold nav')


### running the same strategy multiple times will likely yield different results as underlying data changes

In [ ]:
env.run_strat(buyandhold).bod_nav.plot(title='same strat, different results')
env.run_strat(buyandhold).bod_nav.plot()
env.run_strat(buyandhold).bod_nav.plot()

### comparing the buyandhold and random traders

In [ ]:
# running a strategy multiple times should yield insights 
#   into its expected behavior or give it oppty to learn
bhdf = env.run_strats(buyandhold,100)
rdf = env.run_strats(randomtrader,100)

comparo = pd.DataFrame({'buyhold':bhdf.mean(),
                        'random': rdf.mean()})
comparo

## Object of the game

From the above examples, we can see that buying and holding will, over the long run, give you the market return with low costs.

Randomly trading will instead destroy value rather quickly as costs overwhelm.

### So, what does it mean to win the trading game?  

For our purposes, we'll say that beating a buy & hold strategy, on average, over one hundred episodes will notch a win to the proud ai player.

To support this, the trading environment maintains the *mkt_return* which can be compared with the *sim_return*.

Note that the *mkt_return* is frictionless while the *sim_return* incurs both trading costs and the decay cost of 1 basis point per day, so overcoming the hurdle we've set here should be challenging.


### Playing the game: purloined policy gradients

I've taken and adapted (see [code](policy_gradient.py) for details) a policy gradient implementation based on tensorflow to try to play the single-instrument trading game.  Let's see how it does.

In [1]:
import gym
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import interactive
interactive(True)
import gym_trading

env = gym.make('trading-v0')
#env.time_cost_bps = 0 # 

env = env.unwrapped



import tensorflow as tf
import policy_gradient

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: Environment '<class 'gym_trading.envs.trading_env.TradingEnv'>' has deprecated methods. Compatibility code invoked.


/Users/andrewplaate/miniconda3/envs/mlp/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
INFO:policy_gradient:policy_gradient logger started.


In [2]:
# create the tf session
sess = tf.InteractiveSession()

# create policygradient
pg = policy_gradient.PolicyGradient(sess, obs_dim=6, num_actions=2, learning_rate=1e-2 )

# and now let's train it and evaluate its progress.  NB: this could take some time...
df,sf = pg.train_model(env, episodes=25001, log_freq=100)#, load_model=True)


[[-0.49991614  0.5000838 ]]
[[-0.49941486  0.50058514]]
[[ 0.49842551  0.50157446]]
[[ 0.49901521  0.50098473]]
[[ 0.49953431  0.50046563]]
[[ 0.49965563  0.5003444 ]]
[[-0.50106388  0.49893612]]
[[ 0.49942335  0.50057667]]
[[-0.50019896  0.49980104]]
[[ 0.49930105  0.50069892]]
[[-0.49957088  0.50042915]]
[[ 0.49964121  0.50035876]]
[[-0.49949309  0.500507  ]]
[[ 0.49933785  0.50066215]]
[[-0.49946028  0.50053978]]
[[ 0.49873766  0.50126237]]
[[ 0.49873304  0.50126696]]
[[-0.49955633  0.5004437 ]]
[[ 0.49874917  0.50125086]]
[[-0.49853557  0.50146443]]
[[ 0.49834865  0.50165135]]
[[ 0.49815175  0.50184828]]
[[-0.49801823  0.50198179]]
[[ 0.49799475  0.50200522]]
[[ 0.49797034  0.50202966]]
[[ 0.49809912  0.50190085]]
[[ 0.49818701  0.50181293]]
[[ 0.49825561  0.50174439]]
[[ 0.49869716  0.50130284]]
[[ 0.49920103  0.50079894]]
[[ 0.49980772  0.50019228]]
[[-0.50023741  0.49976254]]
[[ 0.50185168  0.49814835]]
[[-0.49992704  0.5000729 ]]
[[ 0.49999711  0.50000292]]
[[ 0.50008601  0.499

[[ 0.48757425 -0.51242578]]
[[ 0.48850712 -0.51149285]]
[[ 0.48963928 -0.51036072]]
[[ 0.4899424  -0.51005763]]
[[ 0.48984289 -0.51015717]]
[[ 0.49003452 -0.50996548]]
[[ 0.48969057 -0.5103094 ]]
[[ 0.48937371 -0.51062632]]
[[ 0.48903584 -0.51096416]]
[[ 0.48843503 -0.51156497]]
[[ 0.48819488 -0.51180512]]
[[ 0.48862162 -0.51137841]]
[[ 0.48842436 -0.51157564]]
[[ 0.48850912 -0.51149088]]
[[ 0.48854756 -0.51145244]]
[[ 0.48884833 -0.51115173]]
[[ 0.48895174 -0.51104826]]
[[ 0.48862097 -0.511379  ]]
[[ 0.48813951 -0.51186055]]
[[ 0.48770636 -0.51229358]]
[[ 0.48713237 -0.51286763]]
[[ 0.48697597 -0.51302403]]
[[ 0.48670837 -0.51329172]]
[[ 0.48654398 -0.51345605]]
[[ 0.48732376 -0.51267618]]
[[ 0.48766196 -0.51233804]]
[[ 0.48690358 -0.51309639]]
[[ 0.48558542 -0.51441461]]
[[ 0.48542881 -0.51457125]]
[[ 0.48530093 -0.5146991 ]]
[[ 0.48500487 -0.5149951 ]]
[[ 0.48537892 -0.51462102]]
[[ 0.48526776 -0.51473218]]
[[ 0.48509651 -0.51490343]]
[[ 0.48510107 -0.51489896]]
[[ 0.48553619 -0.514

[[ 0.50052631 -0.49947366]]
[[ 0.50001168 -0.49998838]]
[[ 0.49932584 -0.50067413]]
[[ 0.49802792 -0.50197202]]
[[ 0.49834934 -0.50165063]]
[[ 0.4992727  -0.50072736]]
[[ 0.49981445 -0.50018549]]
[[ 0.49976569 -0.50023437]]
[[ 0.50022572 -0.49977428]]
[[ 0.50257272 -0.49742723]]
[[ 0.49962765 -0.50037241]]
[[ 0.49943519 -0.50056481]]
[[ 0.50037056 -0.49962953]]
[[ 0.50048721 -0.49951279]]
[[ 0.50232899 -0.49767101]]
[[ 0.49962392 -0.50037605]]
[[ 0.50156128 -0.49843872]]
[[ 0.49912032 -0.5008797 ]]
[[ 0.50104773 -0.49895233]]
[[ 0.50072479 -0.4992753 ]]
[[ 0.49979329 -0.50020671]]
[[ 0.49801588 -0.50198418]]
[[ 0.49748811 -0.50251186]]
[[ 0.49932456 -0.50067538]]
[[ 0.49918455 -0.50081539]]
[[ 0.50129479 -0.49870518]]
[[ 0.50061572 -0.49938431]]
[[ 0.49883547 -0.5011645 ]]
[[ 0.49998349 -0.50001657]]
[[ 0.50020826 -0.49979171]]
[[ 0.50138277 -0.49861723]]
[[ 0.50075758 -0.4992424 ]]
[[ 0.50193352 -0.49806648]]
[[ 0.5009613  -0.49903873]]
[[ 0.49823344 -0.50176656]]
[[ 0.49732357 -0.502

[[ 0.50051558 -0.49948445]]
[[ 0.50046486 -0.49953514]]
[[ 0.50046873 -0.49953127]]
[[ 0.50063396  0.49936596]]
[[ 0.50012863 -0.49987137]]
[[ 0.50075513 -0.49924484]]
[[ 0.5015955  -0.49840444]]
[[-0.50055212 -0.49944782]]
[[ 0.50002587 -0.49997419]]
[[ 0.50134158 -0.49865842]]
[[ 0.50037742 -0.49962258]]
[[ 0.49984127 -0.50015879]]
[[-0.49919686 -0.50080323]]
[[ 0.50091445 -0.49908555]]
[[ 0.50115383  0.4988462 ]]
[[ 0.50036949 -0.49963054]]
[[-0.50017148 -0.49982849]]
[[ 0.50020331 -0.49979663]]
[[ 0.49928632 -0.50071371]]
[[ 0.50069082 -0.49930915]]
[[ 0.50012988 -0.49987015]]
[[ 0.50030816 -0.49969184]]
[[ 0.49969143 -0.50030857]]
[[ 0.5013321 -0.4986679]]
[[-0.49966225 -0.50033772]]
[[ 0.50126928 -0.49873075]]
[[ 0.5005638  -0.49943623]]
[[ 0.50035936 -0.49964064]]
[[ 0.49966678 -0.50033325]]
[[ 0.500027   -0.49997303]]
[[ 0.50041991 -0.49958009]]
[[ 0.50013202 -0.49986801]]
[[ 0.50022966 -0.49977031]]
[[ 0.49990126 -0.50009871]]
[[-0.4997378 -0.5002622]]
[[ 0.50006539 -0.4999345

[[-0.49591139  0.50408858]]
[[-0.49906671  0.50093329]]
[[-0.49743697  0.502563  ]]
[[-0.49793771  0.50206226]]
[[-0.49618012  0.50381988]]
[[-0.49510235  0.50489765]]
[[-0.49763328  0.50236672]]
[[-0.49485096  0.50514907]]
[[-0.49442196  0.50557804]]
[[-0.49546617  0.50453383]]
[[-0.49556801  0.50443202]]
[[-0.49568504  0.5043149 ]]
[[-0.49287981  0.50712013]]
[[-0.49823987  0.50176013]]
[[-0.49901387  0.50098616]]
[[-0.50015128  0.49984869]]
[[-0.49596375  0.50403625]]
[[-0.50047064  0.49952933]]
[[-0.49781919  0.50218081]]
[[-0.49957877  0.50042117]]
[[-0.49994472  0.50005531]]
[[-0.49971706  0.500283  ]]
[[-0.50163758  0.49836248]]
[[-0.49837235  0.50162774]]
[[-0.499686  0.500314]]
[[-0.49558476  0.50441515]]
[[ 0.50152773 -0.49847227]]
[[-0.50115865  0.49884135]]
[[-0.49913388  0.50086612]]
[[-0.49741828  0.50258172]]
[[-0.5003987   0.49960124]]
[[-0.5001806   0.49981946]]
[[ 0.49825478  0.50174528]]
[[ 0.50022346 -0.49977654]]
[[ 0.49779654 -0.50220346]]
[[ 0.4982492  -0.5017507

[[ 0.47968975 -0.52031028]]
[[ 0.47934243 -0.5206576 ]]
[[ 0.47766545 -0.52233458]]
[[ 0.48109517 -0.51890481]]
[[ 0.48011202 -0.51988798]]
[[ 0.4805586  -0.51944143]]
[[ 0.48161295 -0.51838702]]
[[ 0.48205647 -0.5179435 ]]
[[ 0.48244613 -0.51755393]]
[[ 0.4830738  -0.51692629]]
[[ 0.48307791 -0.51692212]]
[[ 0.48268595 -0.51731408]]
[[ 0.48273808 -0.51726198]]
[[ 0.48256803 -0.51743203]]
[[ 0.48251987 -0.51748013]]
[[ 0.48212555 -0.51787436]]
[[ 0.48222438 -0.51777565]]
[[ 0.48243654 -0.51756346]]
[[ 0.4844054 -0.5155946]]
[[ 0.48430634 -0.51569366]]
[[ 0.48429155 -0.51570851]]
[[ 0.48341045 -0.51658958]]
[[ 0.48418289 -0.51581705]]
[[ 0.4851692  -0.51483083]]
[[ 0.48525131 -0.51474875]]
[[ 0.48523277 -0.51476723]]
[[ 0.48485208 -0.51514798]]
[[ 0.4851225 -0.5148775]]
[[ 0.48446786 -0.51553214]]
[[ 0.48424309 -0.51575685]]
[[ 0.48257899 -0.51742101]]
[[ 0.48466393 -0.51533604]]
[[ 0.48679042 -0.51320952]]
[[ 0.48744136 -0.51255858]]
[[ 0.48705137 -0.51294857]]
[[ 0.48648968 -0.5135102

[[-0.49745685  0.50254309]]
[[-0.4980711   0.50192893]]
[[-0.49822852  0.50177151]]
[[-0.49734387  0.5026561 ]]
[[-0.49798426  0.50201571]]
[[-0.498083    0.50191706]]
[[-0.49926549  0.50073451]]
[[-0.49809557  0.50190443]]
[[-0.49794155  0.50205851]]
[[-0.49676064  0.50323939]]
[[-0.49725544  0.5027445 ]]
[[-0.49677941  0.50322056]]
[[-0.49455291  0.50544715]]
[[-0.49743205  0.50256789]]
[[-0.49788544  0.50211447]]
[[-0.49684691  0.50315315]]
[[-0.49671683  0.5032832 ]]
[[-0.49530956  0.50469041]]
[[-0.49807659  0.50192338]]
[[-0.49617803  0.50382191]]
[[-0.49848577  0.5015142 ]]
[[-0.49705663  0.5029434 ]]
[[-0.49814501  0.50185502]]
[[-0.49937239  0.50062764]]
[[-0.50067288  0.49932712]]
[[-0.50050765  0.49949238]]
[[-0.49774495  0.50225502]]
[[-0.49825025  0.50174975]]
[[-0.49666062  0.50333941]]
[[-0.49733713  0.50266284]]
[[-0.49887246  0.50112754]]
[[-0.49772161  0.50227833]]
[[-0.49704066  0.50295931]]
[[-0.49637145  0.50362861]]
[[-0.49718904  0.50281101]]
[[-0.49619737  0.503

[[-0.49579525  0.50420469]]
[[-0.49723333  0.50276661]]
[[-0.49684405  0.50315601]]
[[-0.497639    0.50236094]]
[[-0.49828899  0.50171101]]
[[-0.4971801   0.50281984]]
[[-0.49910626  0.50089371]]
[[-0.49806964  0.50193036]]
[[-0.4972077  0.5027923]]
[[-0.49659792  0.50340205]]
[[-0.49585977  0.50414014]]
[[-0.49506533  0.50493467]]
[[-0.49522665  0.50477338]]
[[-0.49593812  0.50406188]]
[[-0.49607709  0.50392294]]
[[-0.49545938  0.50454062]]
[[-0.49629256  0.50370741]]
[[-0.49622598  0.50377399]]
[[-0.4965567  0.5034433]]
[[-0.49685937  0.50314057]]
[[-0.49335289  0.50664711]]
[[-0.49461472  0.50538534]]
[[-0.49615449  0.50384545]]
[[-0.49494091  0.50505912]]
[[-0.49530646  0.50469351]]
[[-0.49796823  0.50203174]]
[[-0.49609411  0.50390589]]
[[-0.49612099  0.50387901]]
[[-0.49501958  0.50498039]]
[[-0.49522606  0.50477391]]
[[-0.4961701   0.50382984]]
[ 8.76219145]
[[ 0.48437148 -0.51562846]]
[[ 0.48409748 -0.51590246]]
[[ 0.48369974 -0.51630026]]
[[ 0.4849537  -0.51504636]]
[[ 0.48454

[[ 0.48777765 -0.51222235]]
[[ 0.48701903 -0.512981  ]]
[[ 0.48769102 -0.51230901]]
[[ 0.4884088 -0.5115912]]
[[ 0.48671886 -0.51328105]]
[[ 0.48569453 -0.51430547]]
[[ 0.48623541 -0.51376462]]
[[ 0.48475757 -0.5152424 ]]
[[ 0.48510417 -0.5148958 ]]
[[ 0.48573744 -0.51426256]]
[[ 0.48519954 -0.51480049]]
[[ 0.48466206 -0.515338  ]]
[[ 0.48587462 -0.51412541]]
[[ 0.48580557 -0.51419437]]
[[ 0.48717457 -0.51282537]]
[[ 0.4875021 -0.5124979]]
[[ 0.48682839 -0.51317155]]
[[ 0.48834988 -0.51165009]]
[[ 0.48810571 -0.51189435]]
[[ 0.4892239  -0.51077604]]
[[ 0.48923659 -0.51076341]]
[[ 0.48934993 -0.5106501 ]]
[[ 0.48937276 -0.51062727]]
[[ 0.48899433 -0.51100564]]
[[ 0.49033281 -0.50966722]]
[[ 0.48993769 -0.51006228]]
[[ 0.49139184 -0.50860816]]
[[ 0.48867133 -0.5113287 ]]
[[ 0.4908506  -0.50914937]]
[[ 0.49018532 -0.50981474]]
[[ 0.48860952 -0.51139039]]
[[ 0.4885239 -0.5114761]]
[[ 0.4884735  -0.51152653]]
[[ 0.48887217 -0.51112783]]
[[ 0.48949814 -0.51050186]]
[[ 0.48983219 -0.51016784]

[[-0.4937245   0.50627548]]
[[-0.49310452  0.50689548]]
[[-0.49201205  0.50798792]]
[[-0.49281847  0.50718158]]
[[-0.49461615  0.50538385]]
[[-0.49368411  0.50631589]]
[[-0.49335584  0.50664413]]
[[-0.49268848  0.50731152]]
[[-0.49263254  0.50736743]]
[[-0.49329722  0.50670278]]
[[-0.49332926  0.50667083]]
[[-0.49441671  0.50558323]]
[[-0.49464834  0.50535166]]
[[-0.49537224  0.50462776]]
[[-0.49544516  0.50455481]]
[[-0.49502817  0.5049718 ]]
[[-0.49389225  0.50610775]]
[[-0.49455014  0.50544989]]
[[-0.49557436  0.50442564]]
[[-0.49377564  0.50622433]]
[[-0.49517259  0.50482732]]
[[-0.49504843  0.5049516 ]]
[[-0.49582419  0.50417578]]
[[-0.4966585  0.5033415]]
[[-0.49455649  0.50544351]]
[[-0.49519756  0.50480235]]
[[-0.49376109  0.50623894]]
[[-0.49773937  0.50226068]]
[[-0.49573335  0.50426668]]
[[-0.49596977  0.50403029]]
[[-0.49673408  0.50326598]]
[[-0.4949719   0.50502807]]
[[-0.49613899  0.50386095]]
[[-0.4969475   0.50305253]]
[[-0.49591288  0.50408709]]
[[-0.49639565  0.50360

[[-0.4983581   0.50164187]]
[[-0.49736157  0.50263846]]
[[-0.49813327  0.50186664]]
[[-0.49904495  0.50095505]]
[[-0.49810454  0.50189543]]
[[-0.4989799   0.50102007]]
[[-0.49819398  0.50180608]]
[[-0.49864411  0.50135595]]
[[-0.49746716  0.50253284]]
[[-0.49711949  0.50288051]]
[[-0.49786946  0.50213051]]
[[-0.49706766  0.50293231]]
[[-0.49742946  0.50257057]]
[[-0.49854311  0.50145692]]
[[-0.49847844  0.50152153]]
[[-0.49917227  0.50082773]]
[[-0.49730772  0.50269222]]
[[-0.49783623  0.50216371]]
[[-0.49849659  0.50150347]]
[[-0.49804929  0.50195074]]
[[-0.49725249  0.50274748]]
[[-0.49697819  0.50302184]]
[[-0.49767444  0.50232559]]
[[-0.49728677  0.5027132 ]]
[[-0.49559587  0.50440413]]
[[-0.4962641  0.5037359]]
[[-0.49664736  0.5033527 ]]
[[-0.49574581  0.50425422]]
[[-0.49574378  0.50425625]]
[[-0.49737775  0.50262225]]
[[-0.49609289  0.50390714]]
[[-0.49709076  0.50290924]]
[[-0.49728698  0.50271308]]
[[-0.49735543  0.50264448]]
[[-0.49746034  0.50253969]]
[[-0.49747154  0.50252

[[-0.4978317  0.5021683]]
[[-0.49851266  0.50148737]]
[[-0.49807787  0.50192207]]
[[-0.49727926  0.50272071]]
[[-0.49698046  0.50301957]]
[[-0.49768481  0.50231516]]
[[-0.49734432  0.50265563]]
[[-0.49565807  0.5043419 ]]
[[-0.49625784  0.50374216]]
[[-0.49669969  0.50330031]]
[[-0.49581704  0.50418299]]
[[-0.49578491  0.50421512]]
[[-0.49740928  0.50259072]]
[[-0.4961549   0.50384504]]
[[-0.49712873  0.50287127]]
[-0.57769832]
[[-0.50132197  0.498678  ]]
[[ 0.49855262 -0.50144744]]
[[-0.50195187  0.49804807]]
[[ 0.49806121 -0.50193882]]
[[ 0.49644822 -0.50355172]]
[[ 0.49661273 -0.50338727]]
[[ 0.49592173 -0.50407833]]
[[ 0.49754736 -0.50245267]]
[[ 0.49564636 -0.50435364]]
[[ 0.49583885 -0.50416112]]
[[ 0.49657196 -0.5034281 ]]
[[ 0.49594024 -0.50405985]]
[[ 0.49659041 -0.50340956]]
[[ 0.49739268 -0.50260735]]
[[-0.49726042 -0.50273955]]
[[-0.50237328 -0.49762675]]
[[-0.50155163  0.4984484 ]]
[[-0.50163472  0.49836531]]
[[ 0.49807897 -0.501921  ]]
[[ 0.49824435 -0.50175565]]
[[-0.502

[[-0.49753344  0.50246656]]
[[-0.49906221  0.50093776]]
[[-0.49799076  0.50200921]]
[[-0.49858251  0.50141752]]
[[-0.49858916  0.50141084]]
[[-0.49977514  0.50022489]]
[[-0.49888751  0.5011124 ]]
[[-0.49814263  0.50185734]]
[[-0.49920833  0.50079167]]
[[-0.4983981   0.50160193]]
[[-0.49767575  0.50232422]]
[[-0.49964738  0.50035256]]
[[-0.49684599  0.50315398]]
[[-0.49895579  0.50104421]]
[[-0.49884692  0.50115311]]
[[-0.49952343  0.5004766 ]]
[[-0.49951994  0.50048012]]
[[-0.4981122  0.5018878]]
[[-0.49660385  0.50339609]]
[[-0.49587971  0.50412029]]
[[-0.49615836  0.50384164]]
[[-0.49646911  0.50353086]]
[[-0.4954595  0.5045405]]
[[-0.49533245  0.50466758]]
[[-0.49527174  0.50472826]]
[[-0.49530804  0.50469202]]
[[-0.492102    0.50789803]]
[[-0.49315757  0.50684243]]
[[-0.49434692  0.50565302]]
[[-0.49517214  0.50482786]]
[[-0.49538669  0.50461334]]
[[-0.49426928  0.50573069]]
[[-0.49563017  0.50436985]]
[[-0.49494493  0.50505507]]
[[-0.49468127  0.50531876]]
[[-0.49523365  0.5047664

[[ 0.48905298 -0.51094699]]
[[ 0.48955649 -0.51044351]]
[[ 0.4897362  -0.51026386]]
[[ 0.49044511 -0.50955492]]
[[ 0.49029863 -0.50970131]]
[[ 0.4902716  -0.50972843]]
[[ 0.49065182 -0.50934809]]
[[ 0.48931444 -0.51068556]]
[[ 0.48949471 -0.51050532]]
[[ 0.49065199 -0.50934803]]
[[ 0.49144107 -0.50855893]]
[[ 0.49117666 -0.50882334]]
[[ 0.49096397 -0.50903606]]
[[ 0.49214587 -0.50785416]]
[[ 0.49155533 -0.50844467]]
[[ 0.49241254 -0.50758743]]
[[ 0.49303752 -0.50696248]]
[[ 0.49235535 -0.50764459]]
[[ 0.49357522 -0.50642473]]
[[ 0.49125224 -0.50874782]]
[[ 0.49123046 -0.50876951]]
[[ 0.49154299 -0.50845695]]
[[ 0.49114305 -0.50885689]]
[[ 0.49130446 -0.5086956 ]]
[[ 0.49306425 -0.50693578]]
[[ 0.4921782 -0.5078218]]
[[ 0.49186435 -0.50813562]]
[[ 0.49511591 -0.50488406]]
[[ 0.49831513 -0.5016849 ]]
[[ 0.49387476 -0.50612521]]
[[ 0.49486822 -0.50513184]]
[[ 0.49608424 -0.50391567]]
[[ 0.49341819 -0.50658184]]
[[ 0.49267161 -0.50732839]]
[[ 0.49488139 -0.50511861]]
[[ 0.49842706 -0.50157

[[ 0.50017756  0.4998225 ]]
[[ 0.50032258 -0.49967736]]
[[-0.50051302  0.49948698]]
[[-0.50059175  0.4994083 ]]
[[-0.50034553  0.4996545 ]]
[[ 0.50188845 -0.49811152]]
[[ 0.49921831 -0.50078166]]
[[-0.49921507  0.50078499]]
[[-0.49962991  0.50037014]]
[[-0.49670237  0.50329757]]
[[-0.49822709  0.50177294]]
[[-0.49718681  0.50281316]]
[[-0.49651897  0.50348109]]
[[-0.49745911  0.50254095]]
[[-0.49626979  0.50373018]]
[[-0.49767771  0.50232232]]
[[-0.49619776  0.50380218]]
[[-0.49447772  0.50552231]]
[[-0.49313736  0.50686264]]
[[-0.49539778  0.50460225]]
[[-0.49781469  0.5021854 ]]
[[-0.49412364  0.5058763 ]]
[[-0.49425057  0.50574952]]
[[-0.49399573  0.50600421]]
[[-0.49387503  0.50612497]]
[[-0.49543774  0.50456226]]
[[-0.49359354  0.50640643]]
[[-0.49379194  0.50620806]]
[[-0.49556991  0.50443006]]
[[-0.49474874  0.50525123]]
[[-0.49454358  0.50545639]]
[[-0.49236062  0.50763935]]
[[-0.49290752  0.50709242]]
[[-0.4933807   0.50661933]]
[[-0.49412721  0.50587279]]
[[-0.49345219  0.506

[[-0.49756381  0.50243622]]
[[-0.49746203  0.50253803]]
[[-0.49737224  0.50262767]]
[[-0.49850991  0.50149006]]
[[-0.49735871  0.50264132]]
[[-0.49842978  0.50157022]]
[[-0.49922362  0.50077641]]
[[-0.49824947  0.50175053]]
[[-0.49910212  0.50089788]]
[[-0.49836183  0.50163823]]
[[-0.49874601  0.50125402]]
[[-0.49769861  0.50230139]]
[[-0.49732402  0.50267601]]
[[-0.49801269  0.50198728]]
[[-0.4970952   0.50290489]]
[[-0.49766764  0.50233233]]
[[-0.49871075  0.50128931]]
[[-0.49867442  0.50132561]]
[[-0.49936455  0.5006355 ]]
[[-0.49750748  0.50249249]]
[[-0.49797451  0.50202554]]
[[-0.49872881  0.50127119]]
[[-0.4982762   0.50172383]]
[[-0.49754849  0.50245148]]
[[-0.49711931  0.50288075]]
[[-0.49783644  0.50216347]]
[[-0.49747619  0.50252378]]
[[-0.49576962  0.50423032]]
[[-0.49645701  0.50354296]]
[[-0.49673748  0.50326258]]
[[-0.49590877  0.5040912 ]]
[[-0.49583226  0.50416774]]
[[-0.49762449  0.50237542]]
[[-0.4963066  0.5036934]]
[[-0.49730459  0.50269532]]
[[-0.49748626  0.50251

[[-0.49238005  0.50761992]]
[[-0.49287918  0.50712091]]
[[-0.49215561  0.50784439]]
[[-0.48997572  0.51002425]]
[[-0.48822746  0.51177251]]
[[-0.49108243  0.50891763]]
[[-0.49013674  0.5098632 ]]
[[-0.49042588  0.50957412]]
[[-0.49017403  0.509826  ]]
[[-0.49369228  0.50630772]]
[[-0.48920527  0.51079476]]
[[-0.49247408  0.50752586]]
[[-0.4929052   0.50709474]]
[[-0.49163222  0.50836784]]
[[ 0.50662947 -0.49337044]]
[[-0.49568313  0.50431681]]
[[-0.49409953  0.50590056]]
[[-0.49411717  0.5058828 ]]
[[-0.49315628  0.50684369]]
[[-0.49270278  0.50729722]]
[[-0.49247566  0.50752443]]
[[-0.49107823  0.5089218 ]]
[[-0.49190792  0.50809205]]
[[ 0.51013899 -0.48986104]]
[[-0.49694765  0.50305241]]
[[-0.49528763  0.50471234]]
[[-0.49445394  0.50554609]]
[[ 0.49473658  0.50526339]]
[[-0.49562809  0.50437188]]
[[-0.49403736  0.50596261]]
[[-0.49400786  0.50599223]]
[[-0.49587259  0.50412738]]
[[-0.49513626  0.50486374]]
[[-0.49478489  0.50521505]]
[[-0.49473634  0.50526363]]
[[-0.49358734  0.506

KeyboardInterrupt: 

### Results

Policy gradients beat the trading game!  That said, it doesn't work every time and it seems, looking at the charts below, as though it's a bit of a lucky thing.  But luck counts in the trading game as in life!


In [ ]:
sf['net'] = sf.simror - sf.mktror
#sf.net.plot()
sf.net.expanding().mean().plot()
sf.net.rolling(100).mean().plot()

In [ ]:
sf.net.rolling(100).mean().tail()